# Generated by Django 2.0.7 on 2018-07-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='index',
            field=models.IntegerField(default=0, verbose_name='索引'),
        ),
    ]
